name: Code Integrity Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-integrity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run integrity checks
        run: node .github/scripts/integrity-check.js
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}